# Generated by Django 5.1.3 on 2024-11-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='cars', to='cars.carimage'),
        ),
    ]
